### ISSUE TITLE
Better quick start for UNECE documents

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-unece#10]
Potential input to the guide below. 

—————

The software is called Metanorma-UNECE, is available at this link: https://github.com/riboseinc/metanorma-unece/

Installation instructions can be seen here:
https://www.metanorma.com/overview/getting-started/

### Specific answers to questions

1. Titles: the first line of the document is the title, it is set like this:

```
= This is my title
...
```

2. Bullet points: A line that starts with an asterisk becomes an unordered list, and starting with a dot becomes a numbered list. The important thing is the first list bullet must have a blank line above it to work.

For example:

```
This is how an unordered list is set:

* list item 1
* list item 2
...
```

```
This is how a numbered list is set:

. list item 1
. list item 2
...
```

3. Boxed text: Boxed text is supported with the following syntax. Any text (or text block) that is prefixed with [IMPORTANT] will be rendered inside a box.

For example, (the 4 equal signs are used to mark the beginning and end of the box)

```
[IMPORTANT]
.Business Process Analysis Plus (BPA+)   (<==== This is the box title)
====
Business Process Analysis was initially designed to document and evaluate an import/export process at a given point time and its relative simplicity. It also specifically includes a measurement of the time and cost of the complete range of procedures as one of the main outputs of the analysis. This combination makes it suitable as the basis/core of a trade facilitation monitoring and improvement system.
====
```

4.Images: In the Recommendation 42 file attached you can see images inside. The way to include an image is through the `image::path[]` syntax.

Such as, the following will include an image named “figure2a.png” located in the same directory as the text file.

```
image::figure2a.png[]
```

————

### Getting started for / Testing out UNECE documents

Since this software is still in development it is not yet as mature as the other standards we support. We plan to fully complete support if there is interest.

The easiest way to try out is using a Mac. It takes a little bit more work on a Windows machine through the platform-independent Docker container (see the Quickstart guide) , but it is doable.

The current examples of UNECE documents encoded using Metanorma is provided here:
https://github.com/riboseinc/unece-docs/

(please run the 2-line macOS setup script prior to the following)

First, use Git to clone the code and documents:

```
git clone https://github.com/riboseinc/unece-docs/
```

Then, install all dependencies with this command:
```
bundle
```

Next, run the compilation toolchain:
```
make all
```

Then you will see the files generated, including HTML and Word Doc. The output (HTML + Doc)  is attached to this email.
 
The easiest way to start a new document is to copy one of the two samples and modify them.

————

### UNECE-specific document attributes

We currently support Recommendations and Plenary documents, as described here https://github.com/riboseinc/metanorma-unece#document-attributes.

For Recommendations, the attribute `:docnumber:` provides the document number.

For Plenary documents, there are a number of attributes that can be set:

`:session-date:` Date of the session where this document will be discussed. e.g. Geneva, 30 April – 1 May 2018

`:agenda-item:` Number of the agenda item this document belongs to. e.g. Item 6 of the provisional agenda

`:collaborator:` Collaborator of this document, if any. e.g. World Economic Forum

`:agenda-id:` The unique ID number of this agenda item. e.g. ECE/TRADE/C/CEFACT/2018/6

`:distribution:` Extent of distribution allowed. e.g. General

————

### Explanation

The toolchain works like this (in the case of UNECE documents):

1. The text input is in AsciiDoc (“.adoc”) format.

2. (“Compiling”) The first stage of the converter compiles an XML file we call “UNECE XML”, which is an instance of the StandardDocument model (https://github.com/riboseinc/metanorma-model-standoc/). It is the semantic version of XML that should adheres to most UN editing rules (we haven’t gone through them fully yet).

3. (“Rendering”) The second stage of the converter converts UNECE XML into any kind of output format. The software currently supports Word and HTML outputs. The Word output is “mostly" compliant with the required styling.

The toolchain fully supports all document requirements we encountered in Recommendations — equations, references, tables, footnotes, citations, terms and definitions and annexes. 

The entire toolchain is open-source and offered for free.

### Example

I’ve attached the generated UNECE documents from the sample source at https://github.com/riboseinc/unece-docs

More details

For more details on how to use the toolchain, see the Quickstart guide:

https://www.metanorma.com/overview/getting-started/

**Comment by opoudjis** [comment]
This is a document specific to UNECE, *from scratch*. I will not write such a document.

https://github.com/riboseinc/metanorma-iso/blob/master/docs/quickstart.adoc has been made generic to Metanorma, and now includes a couple of TIPs with UNECE-specific references. I will incorporate some of what you have done here in the UNECE Readme.

**Comment by opoudjis** [comment]
Please review:

* https://github.com/riboseinc/metanorma-unece/blob/master/README.adoc
* https://github.com/riboseinc/metanorma-iso/blob/master/docs/quickstart.adoc
* https://github.com/riboseinc/metanorma-iso/blob/master/docs/guidance.adoc

**Comment by opoudjis** [comment]
I think this is being overtaken by events, i.e. the rewrite by @stroganoff. Putting on hold.

**Comment by opoudjis** [comment]
Actually, given that these documents are now being reviewed anyway, this issue is now obsolete.
